import { geistMono, geistSans } from "@Constants/fonts";
import MainLayout from "@Layout/MainLayout";
import "@Styles/app.scss";
import { uiHelper } from "@Utils/uiHelper";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<script
					// biome-ignore lint/security/noDangerouslySetInnerHtml: Required for scroll restoration control
					dangerouslySetInnerHTML={{
						__html: `history.scrollRestoration = 'manual'`,
					}}
				/>
				{uiHelper.isDevelopment() && (
					<Script src="https://unpkg.com/react-scan/dist/auto.global.js"></Script>
				)}
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
